import type { Chapter } from "./types"

export const mockChapters: Chapter[] = [
  // Physics Chapters
  {
    id: "phys-1",
    name: "Kinematics",
    subject: "physics",
    class: "Class 11",
    unit: "Mechanics",
    status: "Completed",
    progress: 100,
    questionsCount: 45,
    accuracy: 85,
    accuracyChange: 5,
    speed: 70,
    speedChange: 3,
    score: 8.5,
    scoreChange: 0.5,
    isWeak: false,
  },
  {
    id: "phys-2",
    name: "Laws of Motion",
    subject: "physics",
    class: "Class 11",
    unit: "Mechanics",
    status: "In Progress",
    progress: 65,
    questionsCount: 38,
    accuracy: 72,
    accuracyChange: -2,
    speed: 65,
    speedChange: 0,
    score: 7.2,
    scoreChange: -0.3,
    isWeak: true,
  },
  {
    id: "phys-3",
    name: "Work, Energy and Power",
    subject: "physics",
    class: "Class 11",
    unit: "Mechanics",
    status: "Not Started",
    progress: 0,
    questionsCount: 42,
    accuracy: 0,
    accuracyChange: 0,
    speed: 0,
    speedChange: 0,
    score: 0,
    scoreChange: 0,
    isWeak: false,
  },
  {
    id: "phys-4",
    name: "Electrostatics",
    subject: "physics",
    class: "Class 12",
    unit: "Electricity",
    status: "Completed",
    progress: 100,
    questionsCount: 35,
    accuracy: 90,
    accuracyChange: 8,
    speed: 75,
    speedChange: 5,
    score: 9.0,
    scoreChange: 1.0,
    isWeak: false,
  },
  {
    id: "phys-5",
    name: "Current Electricity",
    subject: "physics",
    class: "Class 12",
    unit: "Electricity",
    status: "In Progress",
    progress: 45,
    questionsCount: 40,
    accuracy: 60,
    accuracyChange: -5,
    speed: 55,
    speedChange: -3,
    score: 6.0,
    scoreChange: -0.5,
    isWeak: true,
  },
  {
    id: "phys-6",
    name: "Optics",
    subject: "physics",
    class: "Class 12",
    unit: "Waves",
    status: "Not Started",
    progress: 0,
    questionsCount: 38,
    accuracy: 0,
    accuracyChange: 0,
    speed: 0,
    speedChange: 0,
    score: 0,
    scoreChange: 0,
    isWeak: false,
  },

  // Chemistry Chapters
  {
    id: "chem-1",
    name: "Atomic Structure",
    subject: "chemistry",
    class: "Class 11",
    unit: "Physical Chemistry",
    status: "Completed",
    progress: 100,
    questionsCount: 32,
    accuracy: 88,
    accuracyChange: 6,
    speed: 72,
    speedChange: 4,
    score: 8.8,
    scoreChange: 0.8,
    isWeak: false,
  },
  {
    id: "chem-2",
    name: "Chemical Bonding",
    subject: "chemistry",
    class: "Class 11",
    unit: "Physical Chemistry",
    status: "In Progress",
    progress: 70,
    questionsCount: 36,
    accuracy: 75,
    accuracyChange: 0,
    speed: 68,
    speedChange: 2,
    score: 7.5,
    scoreChange: 0,
    isWeak: false,
  },
  {
    id: "chem-3",
    name: "Organic Chemistry Basics",
    subject: "chemistry",
    class: "Class 11",
    unit: "Organic Chemistry",
    status: "Not Started",
    progress: 0,
    questionsCount: 40,
    accuracy: 0,
    accuracyChange: 0,
    speed: 0,
    speedChange: 0,
    score: 0,
    scoreChange: 0,
    isWeak: false,
  },
  {
    id: "chem-4",
    name: "Thermodynamics",
    subject: "chemistry",
    class: "Class 12",
    unit: "Physical Chemistry",
    status: "Completed",
    progress: 100,
    questionsCount: 38,
    accuracy: 65,
    accuracyChange: -8,
    speed: 60,
    speedChange: -5,
    score: 6.5,
    scoreChange: -0.8,
    isWeak: true,
  },
  {
    id: "chem-5",
    name: "Electrochemistry",
    subject: "chemistry",
    class: "Class 12",
    unit: "Physical Chemistry",
    status: "In Progress",
    progress: 50,
    questionsCount: 34,
    accuracy: 78,
    accuracyChange: 3,
    speed: 70,
    speedChange: 5,
    score: 7.8,
    scoreChange: 0.3,
    isWeak: false,
  },
  {
    id: "chem-6",
    name: "Coordination Compounds",
    subject: "chemistry",
    class: "Class 12",
    unit: "Inorganic Chemistry",
    status: "Not Started",
    progress: 0,
    questionsCount: 30,
    accuracy: 0,
    accuracyChange: 0,
    speed: 0,
    speedChange: 0,
    score: 0,
    scoreChange: 0,
    isWeak: false,
  },

  // Mathematics Chapters
  {
    id: "math-1",
    name: "Functions",
    subject: "mathematics",
    class: "Class 11",
    unit: "Algebra",
    status: "Completed",
    progress: 100,
    questionsCount: 42,
    accuracy: 92,
    accuracyChange: 7,
    speed: 85,
    speedChange: 5,
    score: 9.2,
    scoreChange: 0.7,
    isWeak: false,
  },
  {
    id: "math-2",
    name: "Limits and Derivatives",
    subject: "mathematics",
    class: "Class 11",
    unit: "Calculus",
    status: "In Progress",
    progress: 60,
    questionsCount: 45,
    accuracy: 68,
    accuracyChange: -4,
    speed: 62,
    speedChange: -3,
    score: 6.8,
    scoreChange: -0.4,
    isWeak: true,
  },
  {
    id: "math-3",
    name: "Probability",
    subject: "mathematics",
    class: "Class 11",
    unit: "Statistics",
    status: "Not Started",
    progress: 0,
    questionsCount: 38,
    accuracy: 0,
    accuracyChange: 0,
    speed: 0,
    speedChange: 0,
    score: 0,
    scoreChange: 0,
    isWeak: false,
  },
  {
    id: "math-4",
    name: "Matrices and Determinants",
    subject: "mathematics",
    class: "Class 12",
    unit: "Algebra",
    status: "Completed",
    progress: 100,
    questionsCount: 40,
    accuracy: 95,
    accuracyChange: 10,
    speed: 88,
    speedChange: 8,
    score: 9.5,
    scoreChange: 1.0,
    isWeak: false,
  },
  {
    id: "math-5",
    name: "Integrals",
    subject: "mathematics",
    class: "Class 12",
    unit: "Calculus",
    status: "In Progress",
    progress: 40,
    questionsCount: 48,
    accuracy: 58,
    accuracyChange: -7,
    speed: 50,
    speedChange: -10,
    score: 5.8,
    scoreChange: -0.7,
    isWeak: true,
  },
  {
    id: "math-6",
    name: "Vector Algebra",
    subject: "mathematics",
    class: "Class 12",
    unit: "Vectors",
    status: "Not Started",
    progress: 0,
    questionsCount: 36,
    accuracy: 0,
    accuracyChange: 0,
    speed: 0,
    speedChange: 0,
    score: 0,
    scoreChange: 0,
    isWeak: false,
  },
]
